
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello", action = "http://tempuri.org/Hello")
    @WebResult(name = "HelloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloResponse")
    public String hello(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 
     * @param xmlFormatCommand
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Command", action = "http://tempuri.org/Command")
    @WebResult(name = "CommandResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Command", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Command")
    @ResponseWrapper(localName = "CommandResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CommandResponse")
    public String command(
        @WebParam(name = "xmlFormatCommand", targetNamespace = "http://tempuri.org/")
        String xmlFormatCommand);

}
